logging:
  level:
    root: INFO
spring:
  profiles:
    active: redis
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    repositories:
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: springtest
      username: spring
      password: spring
      authentication-database: admin
      uri: mongodb://spring:spring@localhost:27017/springtest?authSource=admin
security:
  basic:
    enabled: false
server:
  port: 8080

